import json
from pprint import pprint
from bs4 import BeautifulSoup

# Read database data - after it has been encoded in json
json_data = open('db.json')
data = json.load(json_data)[0]['hubot:storage']
macros = json.loads(data)['macros']
json_data.close()

# Sort the data alphabetically
macros = sorted(macros, key=lambda k: k['macro'])

index = 0
count = 1
p_num = 1
while index < len(macros):
  # Generate Page Header
  page = '<!-- THIS FILE WAS AUTO-GENERATED - DO NOT EDIT THIS FILE -->'
  page = page + '<div class="container-2 col-lg-12">';

  # Add the next 16 macros to the page
  while count <= 16 and index < len(macros):
    page = page + '<div class="item col-md-3"><img class="img-responsive" src="' + macros[index]['url'] + '"/><div class="col-md-3 item-title">' + macros[index]['macro'] + '</div></div>'
    count = count + 1
    index = index + 1
  page = page + '</div>'

  # Write the html page
  soup = BeautifulSoup(page)
  fo = open('www/gen/page_' + str(p_num) + '.html', "w+")
  fo.write(soup.prettify())
  fo.close()

  # Increment Variables for next page
  p_num = p_num + 1
  count = 1


# Build the paginator
with open('www/index.html', 'r') as myfile:
  home = myfile.read()
home_page = BeautifulSoup(home)

paginator = home_page.find('ul', {"class":"pagination"})
paginator.clear()

paginator.append('<li id="back" data-min="1"><a href="#">&laquo;</a></li>')
paginator.append('<li id="1" class="p-btn active"><a href="#">1</a></li>')
cur_page = 2
while cur_page < p_num:
  paginator.append('<li id="' + str(cur_page) + '" class="p-btn"><a href="#">' + str(cur_page) + '</a></li>')
  cur_page = cur_page + 1;
paginator.append('<li id="next" data-max="' + str(p_num - 1) + '">' + '<a href="#">&raquo;</a></li>')

# Write new paginator
fo = open('www/index.html', "w+")
fo.write(home_page.prettify(formatter=None))
fo.close()
